# -*- coding: utf-8 -*-
"""a_github_file.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TCga9W_zKAXA98t-D8bwZKROIlK9q8ex
"""

import numpy as np
import pandas as pd

print("Hello Github")